#Margaret Brown & Ruth Shepard
#CS 357: Theory of Computation
#Programming Project: Regular Expression Engine
#Resources: https://youtu.be/fgp0tKWYQWY?si=k6Mdu4-TwxUjIFXe

import regex_engine

def main():
    regex = '^[ABCDEFGHIJKLMNOPQRSTUVWXYZ][abcdefghijklmnopqrstuvwxyz]' 
    string = 'abb'
    [matched, match_pos, match_length] = regex_engine.match(regex, string)
    if matched:
        print(f'match regex: {regex}, string: {string} This test string CAN be generated by the given regex.')
    else:
        print(f'match regex: {regex}, string: {string} This test string CANNOT be generated by the given regex.')

#A-Z All capital alphabet: ABCDEFGHIJKLMNOPQRSTUVWXYZ
#a-z All lowercase alphabet: abcdefghijklmnopqrstuvwxyz
#0-9 Digits: 0123456789

if __name__ == '__main__':
    main()