#Margaret Brown & Ruth Shepard
#CS 357: Theory of Computation
#Programming Project: Regular Expression Engine
#Resources: https://youtu.be/fgp0tKWYQWY?si=k6Mdu4-TwxUjIFXe

import regex_engine


def main():
    regex = '^[ABCDEFGHIJKLMNOPQRSTUVWXYZ][abcdefghijklmnopqrstuvwxyz]' #'^abba+(yes|no)' #'^http://(\\a|\\d)+.(com|net|org)'
    string = 'abb'#'aabaa' #'http://clumsy123computer.com/hey/there'
    [matched, match_pos, match_length] = regex_engine.match(regex, string)
    if matched:
        #print(f'match_regex({regex}, {string}) = {string[match_pos:match_pos + match_length]}')
        print(f'match regex: {regex}, string: {string} This test string CAN be generated by the given regex.')
    else:
        #print(f'match_regex({regex}, {string}) = False')
        print(f'match regex: {regex}, string: {string} This test string CANNOT be generated by the given regex.')

#A-Z All capital alphabet: ABCDEFGHIJKLMNOPQRSTUVWXYZ
#a-z All lowercase alphabet: abcdefghijklmnopqrstuvwxyz


if __name__ == '__main__':
    main()